-- Ensure every category has demo listings, and add two freelancers for the
-- new AI & Otomasyon / Veri & Analitik categories.

INSERT INTO "users" ("id", "name", "email", "passwordHash", "role", "title", "bio", "emailVerified", "suspended", "createdAt", "updatedAt")
VALUES
  ('user-deniz-001', 'Deniz A.', 'deniz@profestia.dev', '$2b$10$K20ngPjf0ZYxdxSQlFYR4.RDkNWS39orguZOLJ9okOUPwbmx7jcEO', 'FREELANCER', 'AI & Otomasyon Danışmanı', 'AI & Otomasyon Danışmanı olarak Deniz, Profestia''da yıllardır profesyonel hizmet veriyor.', now(), false, now(), now()),
  ('user-ayse-001', 'Ayşe Ö.', 'ayse@profestia.dev', '$2b$10$K20ngPjf0ZYxdxSQlFYR4.RDkNWS39orguZOLJ9okOUPwbmx7jcEO', 'FREELANCER', 'Veri Analisti', 'Veri Analisti olarak Ayşe, Profestia''da yıllardır profesyonel hizmet veriyor.', now(), false, now(), now())
ON CONFLICT ("email") DO NOTHING;

INSERT INTO "gigs" ("id", "slug", "title", "description", "coverColor", "published", "sellerId", "categoryId", "createdAt", "updatedAt")
VALUES
  ('gig-yazi-ceviri-ing-001', 'i-ngilizce-turkce-profesyonel-ceviri-yapiyorum', 'İngilizce-Türkçe profesyonel çeviri yapıyorum', 'Teknik dokümanlar, web siteleri ve pazarlama metinlerinizi anlam bütünlüğünü koruyarak İngilizce-Türkçe çeviriyorum.', 'violet', true, (SELECT id FROM "users" WHERE email = 'asli@profestia.dev'), (SELECT id FROM "categories" WHERE slug = 'yazi-ceviri'), now(), now()),
  ('gig-video-2d-intro-001', '2d-logo-animasyonu-ve-marka-intro-su-hazirliyorum', '2D logo animasyonu ve marka intro''su hazırlıyorum', 'Markanızın logosunu akıcı bir 2D animasyona dönüştürüp video içeriklerinizin başına eklenecek profesyonel bir intro hazırlıyorum.', 'emerald', true, (SELECT id FROM "users" WHERE email = 'zeynep@profestia.dev'), (SELECT id FROM "categories" WHERE slug = 'video-animasyon'), now(), now()),
  ('gig-muzik-podcast-001', 'podcast-ve-video-icin-ses-miksaji-ve-duzenleme-yapiyorum', 'Podcast ve video için ses miksajı ve düzenleme yapıyorum', 'Ham ses kayıtlarınızı gürültüden arındırıp seviye dengelemesi yaparak yayına hazır, temiz bir mikse dönüştürüyorum.', 'indigo', true, (SELECT id FROM "users" WHERE email = 'zeynep@profestia.dev'), (SELECT id FROM "categories" WHERE slug = 'muzik-ses'), now(), now()),
  ('gig-muzik-sosyal-001', 'sosyal-medya-videolariniz-icin-muzik-ve-seslendirme-buluyorum', 'Sosyal medya videolarınız için müzik ve seslendirme buluyorum', 'İçeriğinizin tonuna uygun telifsiz müzik seçimi yapıyor, gerektiğinde kısa seslendirme kaydı da sağlıyorum.', 'rose', true, (SELECT id FROM "users" WHERE email = 'elif@profestia.dev'), (SELECT id FROM "categories" WHERE slug = 'muzik-ses'), now(), now()),
  ('gig-danismanlik-pazarlama-001', 'kucuk-isletmeler-icin-pazarlama-stratejisi-danismanligi-veriyorum', 'Küçük işletmeler için pazarlama stratejisi danışmanlığı veriyorum', 'İşletmenizin hedef kitlesini, rakiplerini ve kanallarını analiz ederek uygulanabilir bir pazarlama yol haritası çıkarıyorum.', 'amber', true, (SELECT id FROM "users" WHERE email = 'burak@profestia.dev'), (SELECT id FROM "categories" WHERE slug = 'is-danismanlik'), now(), now()),
  ('gig-danismanlik-teknik-001', 'yazilim-projeniz-icin-teknik-danismanlik-ve-kod-incelemesi-yapiyorum', 'Yazılım projeniz için teknik danışmanlık ve kod incelemesi yapıyorum', 'Mevcut kod tabanınızı inceleyip mimari, performans ve güvenlik açısından somut iyileştirme önerileri sunuyorum.', 'sky', true, (SELECT id FROM "users" WHERE email = 'mert@profestia.dev'), (SELECT id FROM "categories" WHERE slug = 'is-danismanlik'), now(), now()),
  ('gig-egitim-seo-001', 'i-cerik-yazarligi-ve-seo-uzerine-birebir-online-ders-veriyorum', 'İçerik yazarlığı ve SEO üzerine birebir online ders veriyorum', 'SEO uyumlu içerik yazımının temellerini, anahtar kelime araştırmasını ve yazı planlamasını birebir canlı derste anlatıyorum.', 'violet', true, (SELECT id FROM "users" WHERE email = 'asli@profestia.dev'), (SELECT id FROM "categories" WHERE slug = 'egitim-ders'), now(), now()),
  ('gig-egitim-tasarim-001', 'grafik-tasarim-temelleri-online-egitimi-veriyorum', 'Grafik tasarım temelleri online eğitimi veriyorum', 'Tipografi, renk teorisi ve kompozisyon temellerini örneklerle anlatan, yeni başlayanlara yönelik birebir eğitim veriyorum.', 'amber', true, (SELECT id FROM "users" WHERE email = 'can@profestia.dev'), (SELECT id FROM "categories" WHERE slug = 'egitim-ders'), now(), now()),
  ('gig-ai-zapier-001', 'zapier-make-ile-is-sureclerinizi-otomatiklestiriyorum', 'Zapier & Make ile iş süreçlerinizi otomatikleştiriyorum', 'Tekrar eden manuel işlerinizi Zapier veya Make üzerinde kurduğum otomasyon akışlarıyla ortadan kaldırıyorum.', 'indigo', true, (SELECT id FROM "users" WHERE email = 'deniz@profestia.dev'), (SELECT id FROM "categories" WHERE slug = 'ai-otomasyon'), now(), now()),
  ('gig-ai-chatbot-001', 'chatgpt-claude-entegrasyonlu-ai-chatbot-gelistiriyorum', 'ChatGPT/Claude entegrasyonlu AI chatbot geliştiriyorum', 'Web siteniz veya WhatsApp hattınız için müşteri sorularını yanıtlayan, kendi verilerinizle eğitilmiş bir AI chatbot geliştiriyorum.', 'sky', true, (SELECT id FROM "users" WHERE email = 'deniz@profestia.dev'), (SELECT id FROM "categories" WHERE slug = 'ai-otomasyon'), now(), now()),
  ('gig-veri-analiz-001', 'i-sletmeniz-icin-satis-ve-pazarlama-verilerini-analiz-ediyorum', 'İşletmeniz için satış ve pazarlama verilerini analiz ediyorum', 'Ham verilerinizi düzenleyip anlamlı içgörülere dönüştürerek karar alma sürecinize somut veri desteği sağlıyorum.', 'emerald', true, (SELECT id FROM "users" WHERE email = 'ayse@profestia.dev'), (SELECT id FROM "categories" WHERE slug = 'veri-analitik'), now(), now()),
  ('gig-veri-dashboard-001', 'excel-power-bi-ile-interaktif-veri-paneli-dashboard-hazirliyorum', 'Excel/Power BI ile interaktif veri paneli (dashboard) hazırlıyorum', 'Verilerinizi canlı güncellenen, filtrelenebilir bir Power BI veya Excel panelinde tek bakışta takip edilebilir hale getiriyorum.', 'violet', true, (SELECT id FROM "users" WHERE email = 'ayse@profestia.dev'), (SELECT id FROM "categories" WHERE slug = 'veri-analitik'), now(), now())
ON CONFLICT ("slug") DO NOTHING;

INSERT INTO "packages" ("id", "tier", "name", "description", "price", "deliveryDays", "revisionCount", "features", "gigId")
VALUES
  ('pkg-yazi-ceviri-ing-001', 'STANDARD', 'Standart Paket', 'Temel içerik paketi, 2 revizyon ve kaynak dosyalar dahil.', 220, 2, 2, ARRAY['Kaynak dosyalar dahil', '2 revizyon hakkı', 'Ticari kullanım lisansı'], 'gig-yazi-ceviri-ing-001'),
  ('pkg-video-2d-intro-001', 'STANDARD', 'Standart Paket', 'Temel içerik paketi, 2 revizyon ve kaynak dosyalar dahil.', 550, 4, 2, ARRAY['Kaynak dosyalar dahil', '2 revizyon hakkı', 'Ticari kullanım lisansı'], 'gig-video-2d-intro-001'),
  ('pkg-muzik-podcast-001', 'STANDARD', 'Standart Paket', 'Temel içerik paketi, 2 revizyon ve kaynak dosyalar dahil.', 300, 3, 2, ARRAY['Kaynak dosyalar dahil', '2 revizyon hakkı', 'Ticari kullanım lisansı'], 'gig-muzik-podcast-001'),
  ('pkg-muzik-sosyal-001', 'STANDARD', 'Standart Paket', 'Temel içerik paketi, 2 revizyon ve kaynak dosyalar dahil.', 180, 2, 2, ARRAY['Kaynak dosyalar dahil', '2 revizyon hakkı', 'Ticari kullanım lisansı'], 'gig-muzik-sosyal-001'),
  ('pkg-danismanlik-pazarlama-001', 'STANDARD', 'Standart Paket', 'Temel içerik paketi, 2 revizyon ve kaynak dosyalar dahil.', 750, 5, 2, ARRAY['Kaynak dosyalar dahil', '2 revizyon hakkı', 'Ticari kullanım lisansı'], 'gig-danismanlik-pazarlama-001'),
  ('pkg-danismanlik-teknik-001', 'STANDARD', 'Standart Paket', 'Temel içerik paketi, 2 revizyon ve kaynak dosyalar dahil.', 600, 3, 2, ARRAY['Kaynak dosyalar dahil', '2 revizyon hakkı', 'Ticari kullanım lisansı'], 'gig-danismanlik-teknik-001'),
  ('pkg-egitim-seo-001', 'STANDARD', 'Standart Paket', 'Temel içerik paketi, 2 revizyon ve kaynak dosyalar dahil.', 400, 1, 2, ARRAY['Kaynak dosyalar dahil', '2 revizyon hakkı', 'Ticari kullanım lisansı'], 'gig-egitim-seo-001'),
  ('pkg-egitim-tasarim-001', 'STANDARD', 'Standart Paket', 'Temel içerik paketi, 2 revizyon ve kaynak dosyalar dahil.', 450, 1, 2, ARRAY['Kaynak dosyalar dahil', '2 revizyon hakkı', 'Ticari kullanım lisansı'], 'gig-egitim-tasarim-001'),
  ('pkg-ai-zapier-001', 'STANDARD', 'Standart Paket', 'Temel içerik paketi, 2 revizyon ve kaynak dosyalar dahil.', 850, 5, 2, ARRAY['Kaynak dosyalar dahil', '2 revizyon hakkı', 'Ticari kullanım lisansı'], 'gig-ai-zapier-001'),
  ('pkg-ai-chatbot-001', 'STANDARD', 'Standart Paket', 'Temel içerik paketi, 2 revizyon ve kaynak dosyalar dahil.', 1400, 8, 2, ARRAY['Kaynak dosyalar dahil', '2 revizyon hakkı', 'Ticari kullanım lisansı'], 'gig-ai-chatbot-001'),
  ('pkg-veri-analiz-001', 'STANDARD', 'Standart Paket', 'Temel içerik paketi, 2 revizyon ve kaynak dosyalar dahil.', 700, 4, 2, ARRAY['Kaynak dosyalar dahil', '2 revizyon hakkı', 'Ticari kullanım lisansı'], 'gig-veri-analiz-001'),
  ('pkg-veri-dashboard-001', 'STANDARD', 'Standart Paket', 'Temel içerik paketi, 2 revizyon ve kaynak dosyalar dahil.', 950, 6, 2, ARRAY['Kaynak dosyalar dahil', '2 revizyon hakkı', 'Ticari kullanım lisansı'], 'gig-veri-dashboard-001')
ON CONFLICT ("id") DO NOTHING;
