-- İçe aktarılan alıcı (BUYER) kullanıcıları.
--
-- Elle verilen 270 benzersiz isim (293 satırdan tekilleştirildi; tekrar edenler
-- aynı kişi) alıcı hesabı olarak eklenir; admin > Kullanıcılar ekranında varsayılan
-- listede görünürler. İsimler Türkçe kurallarıyla düzgün büyük/küçük harfe getirildi.
--
-- Giriş kapalı: passwordHash bcrypt olmayan bir işarete ayarlı, bcrypt.compare bunu
-- sessizce reddeder. Gerekirse `npm run admin:sifre -- <e-posta> <şifre>` ile açılabilir.
-- E-posta @demo.prosinta.com alt alanında (MX yok). ON CONFLICT DO NOTHING: yeniden
-- çalışsa bile aynı e-posta ikinci kez eklenmez.

INSERT INTO "users"
  ("id", "name", "email", "passwordHash", "role", "emailVerified", "suspended", "synthetic", "createdAt", "updatedAt")
VALUES
  ('buyer-imp-0001', 'Emine Sezgin', 'emine-sezgin-1@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0002', 'Ali Balcı', 'ali-balci-2@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0003', 'İhsan Alkuş', 'ihsan-alkus-3@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0004', 'Bedran Kızıltaş', 'bedran-kiziltas-4@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0005', 'Necla Dal', 'necla-dal-5@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0006', 'Selma Bulut', 'selma-bulut-6@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0007', 'Muhammet Koç', 'muhammet-koc-7@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0008', 'Murat Atmaca', 'murat-atmaca-8@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0009', 'Gökhan Kocaağa', 'gokhan-kocaaga-9@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0010', 'Gamze Önel', 'gamze-onel-10@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0011', 'Abdülmuttalip Sönmez', 'abdulmuttalip-sonmez-11@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0012', 'Güldeniz Durna', 'guldeniz-durna-12@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0013', 'Ali Cevizci', 'ali-cevizci-13@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0014', 'İbrahim Bulut', 'ibrahim-bulut-14@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0015', 'Volkan Gümrükçü', 'volkan-gumrukcu-15@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0016', 'Efe Demir', 'efe-demir-16@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0017', 'Bedirhan Keskin', 'bedirhan-keskin-17@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0018', 'Bedir Şaştımoğlu', 'bedir-sastimoglu-18@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0019', 'Aziz Fırat Yerdelen', 'aziz-firat-yerdelen-19@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0020', 'Yaşar Kara', 'yasar-kara-20@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0021', 'Fatih Yılmaz', 'fatih-yilmaz-21@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0022', 'Veysel Düzgün', 'veysel-duzgun-22@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0023', 'Abdulvahap Esen', 'abdulvahap-esen-23@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0024', 'Eray Çağdaş Seven', 'eray-cagdas-seven-24@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0025', 'Muharrem Çağlar', 'muharrem-caglar-25@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0026', 'Selman Akansel', 'selman-akansel-26@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0027', 'Mustafa Daşkın', 'mustafa-daskin-27@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0028', 'Güler Seymen', 'guler-seymen-28@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0029', 'Ömür Karaaslan', 'omur-karaaslan-29@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0030', 'Ahmet Ayaz', 'ahmet-ayaz-30@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0031', 'Feramuz Subaşı', 'feramuz-subasi-31@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0032', 'Abdurrahman Özen', 'abdurrahman-ozen-32@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0033', 'Mehmet Köksoy', 'mehmet-koksoy-33@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0034', 'Ali Bekçi', 'ali-bekci-34@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0035', 'Davut Yumuşak', 'davut-yumusak-35@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0036', 'Dursun Beken', 'dursun-beken-36@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0037', 'Okan Çiçek', 'okan-cicek-37@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0038', 'Oğuzhan Özşahin', 'oguzhan-ozsahin-38@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0039', 'Mustafa Uzunöz', 'mustafa-uzunoz-39@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0040', 'Saddat Öncü', 'saddat-oncu-40@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0041', 'Gökhan Akdoğan', 'gokhan-akdogan-41@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0042', 'Erman Uysal', 'erman-uysal-42@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0043', 'Hafize Sakarya', 'hafize-sakarya-43@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0044', 'Ramazan Batur', 'ramazan-batur-44@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0045', 'İsmet Güler', 'ismet-guler-45@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0046', 'Sergen Erkan', 'sergen-erkan-46@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0047', 'Seyran Yıldız', 'seyran-yildiz-47@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0048', 'Abdullah Türkdoğru', 'abdullah-turkdogru-48@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0049', 'Rasim Maral', 'rasim-maral-49@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0050', 'Cumali Boğça', 'cumali-bogca-50@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0051', 'Abdulkadir Kotan', 'abdulkadir-kotan-51@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0052', 'Alican Dudu', 'alican-dudu-52@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0053', 'Hamdiye Köse', 'hamdiye-kose-53@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0054', 'Basri Başpınar', 'basri-baspinar-54@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0055', 'Ömer Payza', 'omer-payza-55@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0056', 'Hüseyin Karaduman', 'huseyin-karaduman-56@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0057', 'Özge Aladağ', 'ozge-aladag-57@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0058', 'İhsan Camcı', 'ihsan-camci-58@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0059', 'Emel Yedikardeş', 'emel-yedikardes-59@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0060', 'Yusuf Okan Muhassıl', 'yusuf-okan-muhassil-60@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0061', 'Mustafa Topan', 'mustafa-topan-61@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0062', 'Murat Şahin', 'murat-sahin-62@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0063', 'Avni Şardağ', 'avni-sardag-63@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0064', 'Ahmet Aydın', 'ahmet-aydin-64@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0065', 'Orhan Kasım Ceylan', 'orhan-kasim-ceylan-65@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0066', 'Zehra Eskiler', 'zehra-eskiler-66@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0067', 'Birsen Atan', 'birsen-atan-67@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0068', 'Emre Arslan', 'emre-arslan-68@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0069', 'İzzet Ayvaz', 'izzet-ayvaz-69@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0070', 'Kadir Tunca', 'kadir-tunca-70@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0071', 'Süleyman Çelik', 'suleyman-celik-71@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0072', 'Harun Ergün', 'harun-ergun-72@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0073', 'Abdulkadir Ergün', 'abdulkadir-ergun-73@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0074', 'Eyüp Babur', 'eyup-babur-74@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0075', 'Gökhan Ercan', 'gokhan-ercan-75@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0076', 'Derya Aydoğdu', 'derya-aydogdu-76@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0077', 'Tamer Canki', 'tamer-canki-77@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0078', 'Habib Çalın', 'habib-calin-78@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0079', 'Onur Ersungur', 'onur-ersungur-79@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0080', 'Semih Muhammed Temiz', 'semih-muhammed-temiz-80@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0081', 'Ahmet Alp', 'ahmet-alp-81@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0082', 'Burak Alp Ağçay', 'burak-alp-agcay-82@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0083', 'Halil Kaya', 'halil-kaya-83@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0084', 'Celalettin Hancı', 'celalettin-hanci-84@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0085', 'Serkan Atmaca', 'serkan-atmaca-85@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0086', 'Oğuzcan Korkudan', 'oguzcan-korkudan-86@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0087', 'Mehmet Salim Aksarı', 'mehmet-salim-aksari-87@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0088', 'Gökhan Koçak', 'gokhan-kocak-88@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0089', 'Umut Yaşar Tarkan', 'umut-yasar-tarkan-89@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0090', 'Ersin Aydoğdu', 'ersin-aydogdu-90@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0091', 'Mustafa Kaya', 'mustafa-kaya-91@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0092', 'Mehmet Ercan Altun', 'mehmet-ercan-altun-92@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0093', 'Onur Erçin', 'onur-ercin-93@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0094', 'Mehmet Işık', 'mehmet-isik-94@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0095', 'Firat İşin', 'firat-isin-95@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0096', 'Mehmet Keklik', 'mehmet-keklik-96@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0097', 'Kenan Işık', 'kenan-isik-97@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0098', 'Serkan Güçlü', 'serkan-guclu-98@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0099', 'Muhammed Onur Atmaca', 'muhammed-onur-atmaca-99@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0100', 'Gökhan Kaya', 'gokhan-kaya-100@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0101', 'Yusuf Aytaş', 'yusuf-aytas-101@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0102', 'Ahmet Cem Erdoğdu', 'ahmet-cem-erdogdu-102@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0103', 'Sefa Güngör', 'sefa-gungor-103@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0104', 'Erdal İbek', 'erdal-ibek-104@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0105', 'Hamdi Dündar', 'hamdi-dundar-105@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0106', 'Can Aynalı', 'can-aynali-106@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0107', 'Sami Çalışır', 'sami-calisir-107@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0108', 'Cumahan Yıkılmaz', 'cumahan-yikilmaz-108@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0109', 'Recep Dal', 'recep-dal-109@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0110', 'Yunus Emre Öztürk', 'yunus-emre-ozturk-110@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0111', 'Hüseyin Şahin', 'huseyin-sahin-111@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0112', 'İsmail Tafralı', 'ismail-tafrali-112@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0113', 'Öznur Kıyak', 'oznur-kiyak-113@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0114', 'Erol Özçelik', 'erol-ozcelik-114@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0115', 'Mustafa Korkmaz', 'mustafa-korkmaz-115@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0116', 'Ahmet Şencan', 'ahmet-sencan-116@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0117', 'Coşkun Ören', 'coskun-oren-117@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0118', 'Mehmet Şahin', 'mehmet-sahin-118@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0119', 'Şükrü Memiş', 'sukru-memis-119@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0120', 'Refik Özer', 'refik-ozer-120@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0121', 'İlker Yıldırım', 'ilker-yildirim-121@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0122', 'Seyfettin Torak', 'seyfettin-torak-122@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0123', 'Yunus Emre Kılıç', 'yunus-emre-kilic-123@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0124', 'Gökşen Kaner', 'goksen-kaner-124@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0125', 'Mikail Erten', 'mikail-erten-125@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0126', 'Fevzi Altınok', 'fevzi-altinok-126@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0127', 'Erdal Karadaş', 'erdal-karadas-127@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0128', 'Yılmaz Çolak', 'yilmaz-colak-128@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0129', 'Yunus Karakoç', 'yunus-karakoc-129@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0130', 'Salih Durmaz', 'salih-durmaz-130@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0131', 'Hüseyin Başkaya', 'huseyin-baskaya-131@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0132', 'Soner Eker', 'soner-eker-132@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0133', 'Bilgin Adıgüzel', 'bilgin-adiguzel-133@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0134', 'Dilek Dikici', 'dilek-dikici-134@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0135', 'Muhammed Vefa Kaplan', 'muhammed-vefa-kaplan-135@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0136', 'Fatih Opozturk', 'fatih-opozturk-136@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0137', 'Ümit Çam', 'umit-cam-137@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0138', 'Şerife Berber', 'serife-berber-138@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0139', 'Ayşe Gül', 'ayse-gul-139@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0140', 'Halil Han', 'halil-han-140@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0141', 'Aysem Öztenay Kırmızı', 'aysem-oztenay-kirmizi-141@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0142', 'Emirhan Çil', 'emirhan-cil-142@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0143', 'Cihat Tuna', 'cihat-tuna-143@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0144', 'İsmail Hakkı Kara', 'ismail-hakki-kara-144@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0145', 'Mehmet Özkaynak', 'mehmet-ozkaynak-145@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0146', 'Safiye Pınar Tunçer', 'safiye-pinar-tuncer-146@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0147', 'İsrafil Aksoy', 'israfil-aksoy-147@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0148', 'Yunus Köse', 'yunus-kose-148@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0149', 'Gürkan Palaz', 'gurkan-palaz-149@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0150', 'Furkan Tunçer', 'furkan-tuncer-150@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0151', 'Aydan Algın', 'aydan-algin-151@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0152', 'Ramazan Yalçınkaya', 'ramazan-yalcinkaya-152@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0153', 'Önder Taylan Tatar', 'onder-taylan-tatar-153@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0154', 'Ahmet Mübin Dağlılar', 'ahmet-mubin-daglilar-154@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0155', 'Mümin Özer', 'mumin-ozer-155@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0156', 'Yusuf Bilyan', 'yusuf-bilyan-156@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0157', 'Kazım Pasaoğlu', 'kazim-pasaoglu-157@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0158', 'Mehmet Yılmaz', 'mehmet-yilmaz-158@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0159', 'Muhammet Sağlam', 'muhammet-saglam-159@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0160', 'İlkay Mercan', 'ilkay-mercan-160@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0161', 'Suat Oğur', 'suat-ogur-161@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0162', 'Muhteşem Uğur San', 'muhtesem-ugur-san-162@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0163', 'Halit Halitoğlu', 'halit-halitoglu-163@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0164', 'Yükselolgun Koca', 'yukselolgun-koca-164@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0165', 'İlyas Yurdakul', 'ilyas-yurdakul-165@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0166', 'Fatih Gezer', 'fatih-gezer-166@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0167', 'Ekrem Bükmeci', 'ekrem-bukmeci-167@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0168', 'Enes Umut Erol', 'enes-umut-erol-168@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0169', 'Yaşar Çakırlar', 'yasar-cakirlar-169@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0170', 'Oğuzhan Kekeç', 'oguzhan-kekec-170@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0171', 'Esra Yalçınkaya', 'esra-yalcinkaya-171@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0172', 'Ali Özdemir', 'ali-ozdemir-172@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0173', 'Hüseyin Polat', 'huseyin-polat-173@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0174', 'İsmet Özdemir', 'ismet-ozdemir-174@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0175', 'Ali İhsan Berk', 'ali-ihsan-berk-175@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0176', 'Okan Çelik', 'okan-celik-176@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0177', 'Barış Beylen', 'baris-beylen-177@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0178', 'Özkan Burak Dikmen', 'ozkan-burak-dikmen-178@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0179', 'Gultekin Erdas', 'gultekin-erdas-179@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0180', 'Kemal Yıldırım', 'kemal-yildirim-180@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0181', 'Gökhan Soylu', 'gokhan-soylu-181@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0182', 'Mustafa Sedat Avcı', 'mustafa-sedat-avci-182@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0183', 'Alim Çekin', 'alim-cekin-183@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0184', 'Şaha Kaçmaz', 'saha-kacmaz-184@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0185', 'Cengiz Yılmazer', 'cengiz-yilmazer-185@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0186', 'Kemal Ağca', 'kemal-agca-186@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0187', 'Ekrem Ekmekci', 'ekrem-ekmekci-187@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0188', 'Miktad Can Selen', 'miktad-can-selen-188@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0189', 'Selçuk İlkan Yanık', 'selcuk-ilkan-yanik-189@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0190', 'Ahmet Bütün', 'ahmet-butun-190@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0191', 'Aysun Ay', 'aysun-ay-191@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0192', 'Sergen Koyuncuoğlu', 'sergen-koyuncuoglu-192@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0193', 'Yıldız Durmaz', 'yildiz-durmaz-193@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0194', 'Yunus Murtuğan', 'yunus-murtugan-194@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0195', 'Alperen Kirez', 'alperen-kirez-195@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0196', 'Bircan Koçyiğit', 'bircan-kocyigit-196@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0197', 'Simge Sonçağ', 'simge-soncag-197@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0198', 'Hasan Özcan', 'hasan-ozcan-198@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0199', 'Ulas Kosuk', 'ulas-kosuk-199@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0200', 'Cemal Yurttaş', 'cemal-yurttas-200@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0201', 'Turan Güçer', 'turan-gucer-201@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0202', 'Ayşe Aydıncan Yanbul', 'ayse-aydincan-yanbul-202@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0203', 'İsmail Keskin', 'ismail-keskin-203@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0204', 'Esra Uzun', 'esra-uzun-204@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0205', 'Mehmet Dereli', 'mehmet-dereli-205@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0206', 'Seray Oral', 'seray-oral-206@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0207', 'Mohamed Rami Khettou', 'mohamed-rami-khettou-207@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0208', 'Ömer Demirtaş', 'omer-demirtas-208@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0209', 'Servinaz Tatlı', 'servinaz-tatli-209@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0210', 'Ceyhun Ücelehan', 'ceyhun-ucelehan-210@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0211', 'Burak Dundaş', 'burak-dundas-211@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0212', 'Eda Akçay', 'eda-akcay-212@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0213', 'Gonca Özdemir', 'gonca-ozdemir-213@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0214', 'Berk Selimoğlu', 'berk-selimoglu-214@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0215', 'Ertugrul Oral', 'ertugrul-oral-215@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0216', 'Ömer Efe Altuntaş', 'omer-efe-altuntas-216@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0217', 'Fahrettin Şahin', 'fahrettin-sahin-217@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0218', 'Çağlar Kurt', 'caglar-kurt-218@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0219', 'Levent Utan', 'levent-utan-219@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0220', 'Engin Yıldırım', 'engin-yildirim-220@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0221', 'Abdullah Çatar', 'abdullah-catar-221@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0222', 'Veysel Güllü', 'veysel-gullu-222@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0223', 'Mehmet Bişgin', 'mehmet-bisgin-223@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0224', 'Umutcan Ok', 'umutcan-ok-224@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0225', 'Ümit Tozan', 'umit-tozan-225@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0226', 'Gülşah Pehlivanlar', 'gulsah-pehlivanlar-226@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0227', 'Ferhat Kandemir', 'ferhat-kandemir-227@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0228', 'Hamide Eylem Yıldırım', 'hamide-eylem-yildirim-228@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0229', 'Ahmet Demiryürek', 'ahmet-demiryurek-229@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0230', 'Ali Koç', 'ali-koc-230@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0231', 'Şükran Şancı', 'sukran-sanci-231@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0232', 'Mikail Suli', 'mikail-suli-232@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0233', 'Rahman Arabacıoğlu', 'rahman-arabacioglu-233@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0234', 'Resul Özyolcu', 'resul-ozyolcu-234@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0235', 'Derya Taş', 'derya-tas-235@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0236', 'Semanur Çinar', 'semanur-cinar-236@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0237', 'Mehmet Nurullah Turan', 'mehmet-nurullah-turan-237@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0238', 'Nail Atak', 'nail-atak-238@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0239', 'Evindar Karaduman', 'evindar-karaduman-239@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0240', 'Yakup Durmuş', 'yakup-durmus-240@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0241', 'Engin Akkurt', 'engin-akkurt-241@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0242', 'Mehmet Özalp', 'mehmet-ozalp-242@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0243', 'Gülsüm Erdoğdu', 'gulsum-erdogdu-243@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0244', 'Fatih Kılıç', 'fatih-kilic-244@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0245', 'Yiğit Beyler', 'yigit-beyler-245@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0246', 'Ümit Konma', 'umit-konma-246@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0247', 'Vedat Samurkaş', 'vedat-samurkas-247@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0248', 'Batın Dedebali', 'batin-dedebali-248@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0249', 'Necati Aslan', 'necati-aslan-249@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0250', 'Samed Dankı', 'samed-danki-250@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0251', 'Ercan Ceyhan', 'ercan-ceyhan-251@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0252', 'İzzet Bakan', 'izzet-bakan-252@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0253', 'İdris Alıcı', 'idris-alici-253@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0254', 'Berna Makar', 'berna-makar-254@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0255', 'Serkan Baba', 'serkan-baba-255@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0256', 'Kader Demirtaş', 'kader-demirtas-256@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0257', 'Ferhan Çalışkan', 'ferhan-caliskan-257@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0258', 'Ahmet Çelik', 'ahmet-celik-258@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0259', 'İhsan Deniz', 'ihsan-deniz-259@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0260', 'Cüneyt Köprülü', 'cuneyt-koprulu-260@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0261', 'Shakhzod Baratov', 'shakhzod-baratov-261@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0262', 'Nazım Yeşilordu', 'nazim-yesilordu-262@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0263', 'Zülfikar Akyüz', 'zulfikar-akyuz-263@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0264', 'Bünyamın Kay', 'bunyamin-kay-264@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0265', 'Resul Çakmaktaş', 'resul-cakmaktas-265@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0266', 'İsmail Yörür', 'ismail-yorur-266@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0267', 'Emre Özcan', 'emre-ozcan-267@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0268', 'Hasan Dalga', 'hasan-dalga-268@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0269', 'Ayhan Balin', 'ayhan-balin-269@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now()),
  ('buyer-imp-0270', 'Sercan Ataklar', 'sercan-ataklar-270@demo.prosinta.com', '!import-no-login', 'BUYER', now(), false, false, now(), now())
ON CONFLICT ("email") DO NOTHING;
