-- Repair Turkish wording in seeded gig titles.
--
-- Titles were generated by pairing every subject in a category with every verb, which
-- produced combinations that do not hold up: a voice recording was "composed", a report
-- was "set up", a design was "designed" twice over. The generator now keeps per-subject
-- verb lists, and this statement brings existing rows in line.
--
-- Slugs are deliberately left alone so published links keep working.

UPDATE "gigs" SET "title" =
  regexp_replace(
  regexp_replace(
  regexp_replace(
  regexp_replace(
  regexp_replace(
  regexp_replace(
  regexp_replace(
  regexp_replace(
  regexp_replace(
  regexp_replace(
  regexp_replace(
  regexp_replace("title",
    -- vowel harmony: miks + -lIyorum
    'mikslıyorum', 'miksliyorum'),
    -- "tasarımınızı tasarlıyorum" and friends: drop the doubled noun
    '(Kartvizit|Ambalaj) tasarımınızı', '\1ınızı'),
    'Broşür ve katalog tasarımınızı', 'Broşür ve kataloğunuzu'),
    'El ilanı \(flyer\) tasarımınızı', 'El ilanınızı (flyer)'),
    'Sunum \(PowerPoint\) tasarımınızı', 'Sunumunuzu (PowerPoint)'),
    'Banner ve afiş tasarımınızı', 'Banner ve afişinizi'),
    -- recordings are made, not composed
    '(kaydınızı|bölümünüzü|efektlerinizi|mesajınızı|spotunuzu|prodüksiyonunuzu)( özenle)? besteliyorum', '\1\2 düzenliyorum'),
    -- reports and analyses are prepared, not "set up"
    '(raporunuzu|analizinizi|verilerinizi|segmentasyonunuzu|sorgularınızı)( sıfırdan)? kuruyorum', '\1 hazırlıyorum'),
    -- an installation or a panel is not "reported"
    '(kurulumunuzu|panelinizi|modelinizi|sorgularınızı)( düzenli)? raporluyorum', '\1 yapılandırıyorum'),
    -- consulting is given; documents and processes are not
    '(planınızı|projeksiyonlarınızı|sunumunuzu|stratejinizi|programınızı)( detaylıca)? veriyorum', '\1 hazırlıyorum'),
    '(süreçlerinizi|çalışmanızı|huninizi|sürecinizi|operasyonunuzu)( detaylıca)? veriyorum', '\1 yönetiyorum'),
    -- coaching is not "explained"
    '(koçluğunuzu|danışmanlığınızı)( sabırla)? anlatıyorum', '\1 veriyorum')
WHERE "title" ~ 'mikslıyorum|tasarımınızı tasarlıyorum|tasarımınızı|besteliyorum|kuruyorum|raporluyorum|veriyorum|anlatıyorum';
