-- Freelancer IBAN kayıtlarındaki isimleri düzgün büyük/küçük harfe çeker.
--
-- Ham listede isimler karışık yazılmıştı (kimi tamamı büyük, kimi küçük). Türkçe
-- kurallarıyla (i/İ, ı/I) her kelimenin ilk harfi büyük olacak şekilde düzeltilir;
-- "IBRAHIM" gibi noktalı-i isimleri "İbrahim" olarak elle düzeltildi.

UPDATE "freelancer_ibans" AS f
SET "name" = v.name
FROM (VALUES
    ('friban-0001', 'Ümit Sandıkçı'),
    ('friban-0002', 'Müslüm Bayduz'),
    ('friban-0003', 'Hüseyin Özkan'),
    ('friban-0004', 'Emre Evlioğlu'),
    ('friban-0005', 'Bülent Güleyen'),
    ('friban-0006', 'Ali Salih'),
    ('friban-0007', 'Yıldırım Yıldız'),
    ('friban-0008', 'Enes Buğra Yavuz'),
    ('friban-0009', 'Serkan Akman'),
    ('friban-0010', 'Gencer Özkul'),
    ('friban-0011', 'Büyamin Demir'),
    ('friban-0012', 'Anas Almustafa'),
    ('friban-0013', 'Onurcan Gündoğdu'),
    ('friban-0014', 'Ömer Yatcı'),
    ('friban-0015', 'Ahmet Utku Akdeniz'),
    ('friban-0016', 'Ugur Kartal'),
    ('friban-0017', 'İbrahim Çakı'),
    ('friban-0018', 'Erdi Topuz'),
    ('friban-0019', 'Fatih Akçay'),
    ('friban-0020', 'Abdulgaffar Taşdemir'),
    ('friban-0021', 'Zafer Dalyaprak'),
    ('friban-0022', 'Bengü Hatice Yılmaz'),
    ('friban-0023', 'Ersin Cevik'),
    ('friban-0024', 'Mücahit Arslan'),
    ('friban-0025', 'Gökhan Çengel'),
    ('friban-0026', 'Onur Ersungur'),
    ('friban-0027', 'Mikail Turan'),
    ('friban-0028', 'Emre Kaleşi'),
    ('friban-0029', 'Feyzullah Yavuz'),
    ('friban-0030', 'Ümit İlingi'),
    ('friban-0031', 'Musa Onur'),
    ('friban-0032', 'Memiş İslam Gökyıldız'),
    ('friban-0033', 'İbrahim Acar'),
    ('friban-0034', 'Ümit Çetinkaya'),
    ('friban-0035', 'Nuri Can Doğanbek'),
    ('friban-0036', 'Mustafa Karalı'),
    ('friban-0037', 'Merve Ordukaya'),
    ('friban-0038', 'Halil İbrahim Akdaş'),
    ('friban-0039', 'Betül Kaplan'),
    ('friban-0040', 'Reber Acar'),
    ('friban-0041', 'Ahmet Korkmaz'),
    ('friban-0042', 'Senem Oğuz'),
    ('friban-0043', 'Volkan Karaoğlu'),
    ('friban-0044', 'Erhan Bostancı'),
    ('friban-0045', 'Şükran Şancı'),
    ('friban-0046', 'Tunahan Namlı'),
    ('friban-0047', 'İbrahim Tekdemir'),
    ('friban-0048', 'İrem Çapar'),
    ('friban-0049', 'Şahan Akpınar'),
    ('friban-0050', 'Hüseyin Artok'),
    ('friban-0051', 'Halil İbrahim Şahin'),
    ('friban-0052', 'Emre Turan'),
    ('friban-0053', 'Erhan Çetin'),
    ('friban-0054', 'Hasan Tanrıverdi'),
    ('friban-0055', 'Mehmet Emin Kömürcü'),
    ('friban-0056', 'Mehmet Akbaş'),
    ('friban-0057', 'Kazım Şahin'),
    ('friban-0058', 'Umut Yılmaz'),
    ('friban-0059', 'Emre Savar'),
    ('friban-0060', 'Burak Demirci'),
    ('friban-0061', 'Dilara Vardar'),
    ('friban-0062', 'Nurhan Selin Atabey'),
    ('friban-0063', 'Abdullah Yurtlu'),
    ('friban-0064', 'Tuncay Bilir'),
    ('friban-0065', 'Sadık Eş'),
    ('friban-0066', 'Doğukan Erdurgun'),
    ('friban-0067', 'Yıldırım Şahin'),
    ('friban-0068', 'Emrah İhtiyar'),
    ('friban-0069', 'Erman Yılmaz'),
    ('friban-0070', 'Hayrullah Kısakol'),
    ('friban-0071', 'Onur Türk'),
    ('friban-0072', 'Kenan Polat'),
    ('friban-0073', 'Songül Tuslak'),
    ('friban-0074', 'İsmail Hakkı Kara'),
    ('friban-0075', 'Meltem Toğlan'),
    ('friban-0076', 'Mümin Özer'),
    ('friban-0077', 'Hafize Sakarya'),
    ('friban-0078', 'Mehmet Aydın'),
    ('friban-0079', 'Berkan Saygın'),
    ('friban-0080', 'Reşat Göktürk'),
    ('friban-0081', 'Betül Ersoy'),
    ('friban-0082', 'Oğuzhan Aktürk'),
    ('friban-0083', 'Muslihittin Ateş'),
    ('friban-0084', 'Kartal Veziroğlu'),
    ('friban-0085', 'Süleyman Can Acısu'),
    ('friban-0086', 'Murat Durak'),
    ('friban-0087', 'Gökay Güney'),
    ('friban-0088', 'Recep Atiş'),
    ('friban-0089', 'Savaş Çalım'),
    ('friban-0090', 'Özkan Gel'),
    ('friban-0091', 'Görkem Düzgün'),
    ('friban-0092', 'Berkay Erdi Aydoğdu'),
    ('friban-0093', 'Bedri Uçar'),
    ('friban-0094', 'Berat Seçgin'),
    ('friban-0095', 'Mehmet Aslantaş'),
    ('friban-0096', 'Özkan Kandemir'),
    ('friban-0097', 'Dilara Kaya'),
    ('friban-0098', 'Bayram Candan'),
    ('friban-0099', 'Sefa Gül'),
    ('friban-0100', 'Erkan Öztürk'),
    ('friban-0101', 'Mert Varol'),
    ('friban-0102', 'Volkan Sevinç'),
    ('friban-0103', 'Kerim Kaçak'),
    ('friban-0104', 'İrem Özel Tuğlu'),
    ('friban-0105', 'Ceyhun Mutlu'),
    ('friban-0106', 'Ahmet Karadeniz'),
    ('friban-0107', 'Mustafa Akın'),
    ('friban-0108', 'Yusuf Emre Yaplıcan'),
    ('friban-0109', 'Hasan Ozel'),
    ('friban-0110', 'Avni Şardağ'),
    ('friban-0111', 'Orhan İpek'),
    ('friban-0112', 'Mehmet Nurullah Turan'),
    ('friban-0113', 'Mehmet Şahin'),
    ('friban-0114', 'Özkan İlal'),
    ('friban-0115', 'Volkan Barışkan'),
    ('friban-0116', 'Mutlu Süyüm'),
    ('friban-0117', 'Ercan Şeremet'),
    ('friban-0118', 'Halide Gezgin'),
    ('friban-0119', 'Ahmet Aydan'),
    ('friban-0120', 'Çetin Gör'),
    ('friban-0121', 'Ayse Erkan'),
    ('friban-0122', 'Bilal Tıkız'),
    ('friban-0123', 'İsmail Sarıgül'),
    ('friban-0124', 'Savaş Karatay'),
    ('friban-0125', 'Erdal Sürücü'),
    ('friban-0126', 'Büşra Demirbaş'),
    ('friban-0127', 'Celal Ergene'),
    ('friban-0128', 'İbrahim Efe Kömürcü'),
    ('friban-0129', 'Kenan Ermin'),
    ('friban-0130', 'Aytekin Süvari'),
    ('friban-0131', 'Gül Yaşar'),
    ('friban-0132', 'Enes Songur'),
    ('friban-0133', 'Berkant Keleş'),
    ('friban-0134', 'Güvercin Uyan'),
    ('friban-0135', 'Sinan Esen'),
    ('friban-0136', 'Bazen Ekiz'),
    ('friban-0137', 'Mustafa Taştan'),
    ('friban-0138', 'Ayşe Kocabaş'),
    ('friban-0139', 'Selami Şimşek'),
    ('friban-0140', 'Tamer Canki'),
    ('friban-0141', 'Mehmet Zafer Özdemir'),
    ('friban-0142', 'Mevlüt Çalıkuşu'),
    ('friban-0143', 'Ali Uzun'),
    ('friban-0144', 'Belgin Yavuz'),
    ('friban-0145', 'Ramazan Aslan'),
    ('friban-0146', 'Duygu Karademir'),
    ('friban-0147', 'Nurcennet Buyakutluğ'),
    ('friban-0148', 'Hasan Hüseyin Yılmaz'),
    ('friban-0149', 'Barış Avcı'),
    ('friban-0150', 'Ebru Uyanık'),
    ('friban-0151', 'Bora Gedik'),
    ('friban-0152', 'Tülay Savaş'),
    ('friban-0153', 'Özgür Deniz Kaya'),
    ('friban-0154', 'Cansel Özmen'),
    ('friban-0155', 'Soner Zeybek'),
    ('friban-0156', 'Evindar Karaduman'),
    ('friban-0157', 'Esma Ocak'),
    ('friban-0158', 'Yeşim Aygün'),
    ('friban-0159', 'Şahin Çobanoğlu'),
    ('friban-0160', 'Emrecan Erdenler'),
    ('friban-0161', 'Alperen Başkan')
) AS v(id, name)
WHERE f.id = v.id;
